nodeLinker: node-modules

packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"
<<<<<<< HEAD

yarnPath: .yarn/releases/yarn-3.6.0.cjs
=======
>>>>>>> 532c93c64bba122a10cc9b59d43be559185920b5
