export {ReactComponent as SildeImg} from './images/SildeImg.svg';
export {ReactComponent as Delete} from './images/Delete.svg';
export {ReactComponent as Arrow} from './images/Arrow.svg';
export {ReactComponent as Coupon} from './images/Coupon.svg';
export {ReactComponent as FooterLogo} from './images/FooterLogo.svg';
export {ReactComponent as StarFill} from './images/StarFill.svg';
export {ReactComponent as PageNext} from './images/PageNext.svg';
export {ReactComponent as PagePrev} from './images/PagePrev.svg';
export {ReactComponent as Logo} from './images/Logo.svg';
export {ReactComponent as Category} from './images/Category.svg';
export {ReactComponent as Kakao} from './images/kakao.svg';
export {ReactComponent as Google} from './images/google.svg';
export {ReactComponent as Naver} from './images/naver.svg';
export {ReactComponent as BrandLogo} from './images/brandlogo.svg';
export {ReactComponent as Search} from './images/Search.svg';
export {ReactComponent as HeartFill} from './images/heart-fill.svg';
export {ReactComponent as Link} from './images/link.svg';
export {ReactComponent as ArrowBottom} from './images/arrow-bottom.svg';
export {ReactComponent as Play} from './images/play.svg';
export {ReactComponent as Circle} from './images/circle.svg';
export {ReactComponent as MoreBtn} from './images/more-btn.svg';
export {ReactComponent as Exclamation} from './images/exclamation-circle.svg';
export {ReactComponent as PlusCircle} from './images/plus-circle.svg';
export {ReactComponent as Pencil} from './images/pencil.svg';
export {ReactComponent as Trash} from './images/trash.svg';
export {ReactComponent as Close} from './images/close.svg';
export {ReactComponent as Stamp} from './images/Stamp.svg';
export {ReactComponent as Email} from './images/Email.svg';
export {ReactComponent as SignupFailure} from './images/SignupFailure.svg';
export {ReactComponent as SignupSuccess} from './images/SignupSuccess.svg';

export { ReactComponent as CertIcon } from "./images/CertIcon.svg";
export { ReactComponent as GameIcon } from "./images/GameIcon.svg";
export { ReactComponent as JavaIcon } from "./images/JavaIcon.svg";
export { ReactComponent as JsIcon } from "./images/JsIcon.svg";
export { ReactComponent as MobileIcon } from "./images/MobileIcon.svg";
export { ReactComponent as NetworkIcon } from "./images/NetworkIcon.svg";
export { ReactComponent as ReactIcon } from "./images/ReactIcon.svg";
export { ReactComponent as SQLIcon } from "./images/SQLIcon.svg";
export { ReactComponent as TestIcon } from "./images/TestIcon.svg";
export { ReactComponent as AIIcon } from "./images/AIIcon.svg";
export { ReactComponent as BlockIcon } from "./images/BlockIcon.svg";
export { ReactComponent as DevIcon } from "./images/DevIcon.svg";
export { ReactComponent as ScureIcon } from "./images/ScureIcon.svg";
export { ReactComponent as NoSearch } from "./images/NoSearch.svg";


;