export { ReactComponent as SubAdv1 } from "./images/SubAdv1.svg";
export { ReactComponent as MainVisual } from "./images/MainVisual.svg";
export { ReactComponent as Delete } from "./images/Delete.svg";
export { ReactComponent as Arrow } from "./images/Arrow.svg";
export { ReactComponent as Coupon } from "./images/Coupon.svg";
export { ReactComponent as FooterLogo } from "./images/FooterLogo.svg";
// export { ReactComponent as Check } from "./Check.svg";
export { ReactComponent as StarFill } from "./images/StarFill.svg";
export { ReactComponent as PageNext } from "./images/PageNext.svg";
export { ReactComponent as PagePrev } from "./images/PagePrev.svg";
export { ReactComponent as Logo } from "./images/Logo.svg";
export { ReactComponent as Category } from "./images/Category.svg";
export { ReactComponent as Kakao } from "./images/kakao.svg";
export { ReactComponent as Google } from "./images/google.svg";
export { ReactComponent as Naver } from "./images/naver.svg";
export { ReactComponent as BrandLogo } from "./images/brandlogo.svg";
