export const toolbarOptions = [
  [{ header: "1" }, { header: "2" }, { header: [1, 2, 3, 4, false] }],
  ["bold", "italic", "underline", "strike"],
  [{ color: [] }, { background: [] }],
  [{ list: "ordered" }, { list: "bullet" }, { list: "check" }],
  [{ indent: "-1" }, { indent: "+1" }],
  [{ align: [] }, { direction: "rtl" }],
  ["link", "image"],
  ["code-block"],
  [{ script: "sub" }, { script: "super" }],
  [{ table: true }],
];
export  const formats = [
  "header",
  "bold",
  "italic",
  "underline",
  "strike",
  "color",
  "background",
  "list",
  "bullet",
  "check",
  "indent",
  "align",
  "direction",
  "link",
  "image",
  "code-block",
  "script",
  "table",
];
